#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BUILD_ENV=local

FROM ubuntu AS local
ONBUILD COPY hadoop-*.tar.gz /opt
ONBUILD COPY apache-tez-*-bin.tar.gz /opt

FROM ubuntu AS release
ARG HADOOP_VERSION
ARG TEZ_VERSION
ONBUILD RUN apt-get update && apt-get -y install wget
ONBUILD RUN wget --no-verbose https://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz && \
           wget --no-verbose https://downloads.apache.org/tez/$TEZ_VERSION/apache-tez-$TEZ_VERSION-bin.tar.gz
ONBUILD RUN mv hadoop-$HADOOP_VERSION.tar.gz /opt && \
           mv apache-tez-$TEZ_VERSION-bin.tar.gz /opt

FROM ubuntu AS hybrid
ARG HADOOP_VERSION
ARG TEZ_VERSION
ONBUILD RUN apt-get update && apt-get -y install wget
ONBUILD RUN wget --no-verbose https://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz
ONBUILD COPY ./apache-tez-$TEZ_VERSION-bin.tar.gz /opt
ONBUILD RUN mv hadoop-$HADOOP_VERSION.tar.gz /opt

FROM ${BUILD_ENV} AS env
ARG HADOOP_VERSION
ARG TEZ_VERSION

RUN tar -xzv \
      --exclude="hadoop-$HADOOP_VERSION/share/doc" \
      --exclude="*/jdiff" \
      --exclude="*/sources" \
      --exclude="*tests.jar" \
      --exclude="*/webapps" \
      -f /opt/hadoop-$HADOOP_VERSION.tar.gz \
      -C /opt/ && \
    tar -xzv \
      --exclude="apache-tez-$TEZ_VERSION-bin/share" \
      -f /opt/apache-tez-$TEZ_VERSION-bin.tar.gz \
      -C /opt

FROM eclipse-temurin:21.0.3_9-jre-ubi9-minimal AS run

ARG UID=1000
ARG HADOOP_VERSION
ARG TEZ_VERSION

RUN set -ex; \
    microdnf update -y; \
    microdnf -y install procps gettext; \
    microdnf clean all; \
    useradd --no-create-home -s /sbin/nologin -c "" --uid $UID hive

ENV HADOOP_HOME=/opt/hadoop \
    TEZ_HOME=/opt/tez

ENV PATH=$HADOOP_HOME/bin:$PATH

COPY --from=env --chown=hive /opt/hadoop-$HADOOP_VERSION $HADOOP_HOME
COPY --from=env --chown=hive /opt/apache-tez-$TEZ_VERSION-bin $TEZ_HOME

COPY --chown=hive entrypoint-am.sh /entrypoint-am.sh

RUN chmod +x /entrypoint-am.sh

USER hive
WORKDIR $HADOOP_HOME

ENTRYPOINT ["/entrypoint-am.sh"]

